export const getHtmlTemplate = () => `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generated by CodeSmith2View</title>
    <!-- Tailwind CSS for styling -->
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        body { font-family: sans-serif; }
    </style>
</head>
<body class="bg-gray-100 flex flex-col items-center justify-center min-h-screen p-4">
    <div class="bg-white p-8 rounded-xl shadow-xl text-center max-w-md w-full">
        <div class="mb-4">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16 text-blue-500 mx-auto" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
            </svg>
        </div>
        <h1 class="text-3xl font-bold text-gray-800 mb-2">It Works!</h1>
        <p class="text-gray-600 mb-6">
            This is your new HTML page generated by <strong>CodeSmith2View</strong>. 
            You can replace this code with your own AdSense landing page content.
        </p>
        <div class="space-y-3">
            <button class="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-4 rounded-lg transition">
                Call to Action
            </button>
            <button class="w-full bg-gray-200 hover:bg-gray-300 text-gray-800 font-semibold py-3 px-4 rounded-lg transition">
                Learn More
            </button>
        </div>
    </div>
    <footer class="mt-8 text-gray-500 text-sm">
        Generated on CodeSmith2View.com
    </footer>
</body>
</html>`;